import { useEffect, useState } from "react";
import { ArrowLeft, Check, ExternalLink, Loader2, X } from "lucide-react";
import { supabase } from "../lib/supabase";

type Pilot = { id: string; protocolo: string; nome_completo: string; cpf: string; telefone: string | null; veiculo: string; numero_carro: string | null; categoria: string; status: string; proof_path: string | null; comprovante_url: string | null; proof_filename: string | null };

export default function AdminRegistrationDetail({ id }: { id: string }) {
  const [pilot, setPilot] = useState<Pilot | null>(null); const [proofUrl, setProofUrl] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { (async () => { const { data, error: queryError } = await supabase.from("pilotos").select("id,protocolo,nome_completo,cpf,telefone,veiculo,numero_carro,categoria,status,proof_path,comprovante_url,proof_filename").eq("id", id).maybeSingle(); if (queryError || !data) { setError(queryError?.message ?? "Inscrição não encontrada."); return; } setPilot(data as Pilot); const path = data.proof_path ?? data.comprovante_url; if (path && !/^https?:\/\//i.test(path)) { const signed = await supabase.storage.from("comprovantes").createSignedUrl(path, 600); if (!signed.error) setProofUrl(signed.data.signedUrl); } else if (path) setProofUrl(path); })(); }, [id]);
  async function review(approved: boolean) { if (!pilot) return; const reason = approved ? null : window.prompt("Motivo da rejeição (opcional):"); setBusy(true); const { error: reviewError } = await supabase.rpc("review_payment", { p_piloto_id: pilot.id, p_approved: approved, p_reason: reason }); setBusy(false); if (reviewError) setError(reviewError.message); else setPilot({ ...pilot, status: approved ? "credenciamento_liberado" : "rejeitado" }); }
  if (error) return <main className="min-h-screen bg-[#171615] p-8 text-red-300">{error}</main>;
  if (!pilot) return <main className="flex min-h-screen items-center justify-center bg-[#171615]"><Loader2 className="animate-spin text-[#c6ff4d]" /></main>;
  return <main className="min-h-screen bg-[#171615] px-4 py-6 text-[#f3f1ea] sm:px-8"><div className="mx-auto max-w-5xl"><a href="/admin/inscricoes" className="mb-6 inline-flex items-center gap-2 text-xs uppercase text-[#a6a196] hover:text-white"><ArrowLeft size={15} /> Solicitações</a><h1 className="font-display text-2xl font-bold uppercase">Análise da inscrição</h1><div className="mt-6 grid gap-5 md:grid-cols-2"><section className="rounded-2xl border border-[#3a3836] bg-[#201f1d] p-6"><p className="font-mono text-xs text-[#a6a196]">{pilot.protocolo}</p><h2 className="mt-4 text-xl font-semibold">{pilot.nome_completo}</h2><div className="mt-6 space-y-3 text-sm text-[#a6a196]"><p><strong className="text-[#f3f1ea]">CPF:</strong> {pilot.cpf}</p><p><strong className="text-[#f3f1ea]">WhatsApp:</strong> {pilot.telefone ?? "-"}</p><p><strong className="text-[#f3f1ea]">Veículo:</strong> {pilot.veiculo}</p><p><strong className="text-[#f3f1ea]">Número:</strong> {pilot.numero_carro ?? "-"}</p><p><strong className="text-[#f3f1ea]">Categoria:</strong> {pilot.categoria}</p><p><strong className="text-[#f3f1ea]">Status:</strong> {pilot.status}</p></div></section><section className="rounded-2xl border border-[#3a3836] bg-[#201f1d] p-6"><h2 className="font-semibold">Comprovante PIX</h2>{proofUrl ? <><a href={proofUrl} target="_blank" rel="noreferrer" className="mt-5 flex items-center gap-2 text-sm text-[#c6ff4d] hover:underline">Abrir {pilot.proof_filename ?? "comprovante"} <ExternalLink size={15} /></a><iframe title="Comprovante PIX" src={proofUrl} className="mt-5 h-72 w-full rounded-xl border border-white/10 bg-white" /></> : <p className="mt-5 text-sm text-[#a6a196]">Nenhum comprovante anexado.</p>}{pilot.status === "comprovante_enviado" && <div className="mt-7 flex gap-3"><button disabled={busy} onClick={() => review(true)} className="inline-flex items-center gap-2 rounded-full bg-[#c6ff4d] px-4 py-2.5 text-xs font-bold uppercase text-[#171615]"><Check size={14} /> Aprovar pagamento</button><button disabled={busy} onClick={() => review(false)} className="inline-flex items-center gap-2 rounded-full border border-red-500/50 px-4 py-2.5 text-xs uppercase text-red-300"><X size={14} /> Rejeitar</button></div>}</section></div></div></main>;
}
