import { useEffect, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import { CarFront, Loader2, ShieldCheck } from "lucide-react";
import { supabase } from "../lib/supabase";

type Passport = { protocolo: string; nome: string; veiculo: string; categoria: string; status: string; statusCheckin: boolean; rejectionReason: string | null; qrToken: string | null };
const statusLabel: Record<string, string> = { aguardando_pagamento: "Aguardando pagamento", comprovante_enviado: "Comprovante em análise", pagamento_aprovado: "Pagamento aprovado", credenciamento_liberado: "Credenciamento liberado", aprovado: "Credenciamento liberado", rejeitado: "Pagamento rejeitado" };

export default function DigitalPassport() {
  const [data, setData] = useState<Passport | null>(null); const [error, setError] = useState("");
  useEffect(() => { const token = localStorage.getItem("topstreet_resume_token"); if (!token) { setError("Não encontramos sua inscrição neste aparelho."); return; } supabase.functions.invoke("registration-status", { body: { token } }).then(({ data: response, error: invokeError }) => { if (invokeError || !response?.status) setError(response?.message ?? "Não foi possível consultar o status."); else setData(response as Passport); }); }, []);
  return <main className="flex min-h-screen items-center justify-center bg-[#171615] px-4 py-8 text-[#f3f1ea]"><section className="w-full max-w-md rounded-3xl border border-[#4a473f] bg-[#201f1d] p-6 text-center shadow-2xl"><div className="mx-auto mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-[#c6ff4d] text-[#171615]"><CarFront /></div><p className="text-xs uppercase tracking-[0.3em] text-[#a6a196]">Top Street · Inscrição</p>{!data && !error && <Loader2 className="mx-auto mt-10 animate-spin text-[#c6ff4d]" />}{error && <p className="mt-8 text-sm text-red-300">{error}</p>}{data && <><h1 className="font-display mt-3 text-2xl font-bold uppercase">{statusLabel[data.status] ?? data.status}</h1><p className="mt-2 font-mono text-xs text-[#a6a196]">{data.protocolo}</p><div className="mt-7 grid gap-2 text-left text-sm"><p><strong>Piloto:</strong> {data.nome}</p><p><strong>Veículo:</strong> {data.veiculo}</p><p><strong>Categoria:</strong> {data.categoria}</p></div>{data.status === "rejeitado" && data.rejectionReason && <p className="mt-5 rounded-xl bg-red-500/10 p-3 text-left text-sm text-red-300">Motivo: {data.rejectionReason}</p>}{data.qrToken && !data.statusCheckin ? <><div className="mx-auto my-7 flex w-fit rounded-2xl bg-white p-4"><QRCodeSVG value={data.qrToken} size={210} /></div><p className="flex items-center justify-center gap-2 text-xs text-[#c6ff4d]"><ShieldCheck size={15} /> Apresente este QR Code na entrada</p></> : data.status === "credenciamento_liberado" && <p className="mt-7 rounded-xl border border-[#c6ff4d]/30 p-4 text-sm text-[#c6ff4d]">Este QR Code já foi utilizado.</p>}</>}</section></main>;
}
