import { FormEvent, useState } from "react";
import { ArrowLeft, KeyRound, Loader2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { maskCPF, maskWhatsApp } from "../lib/validation";
import { supabase } from "../lib/supabase";

export default function PilotLogin() {
  const navigate = useNavigate(); const [cpf, setCpf] = useState(""); const [phone, setPhone] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); const { data, error: invokeError } = await supabase.functions.invoke("pilot-login", { body: { cpf, telefone: phone } }); setBusy(false); if (invokeError || !data?.resumeToken) { setError(data?.message ?? "CPF ou WhatsApp não conferem."); return; } localStorage.setItem("topstreet_resume_token", data.resumeToken); localStorage.setItem("topstreet_protocol", data.protocolo); navigate("/passaporte"); }
  return <main className="flex min-h-screen items-center justify-center bg-[#171615] px-4 py-8 text-[#f3f1ea]"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-[#3a3836] bg-[#201f1d] p-6 sm:p-8"><button type="button" onClick={() => navigate("/")} className="mb-8 inline-flex items-center gap-2 text-xs uppercase text-[#a6a196] hover:text-[#f3f1ea]"><ArrowLeft size={15} /> Voltar</button><KeyRound className="text-[#c6ff4d]" /><h1 className="mt-4 font-display text-2xl font-bold uppercase">Acessar inscrição</h1><p className="mt-2 text-sm text-[#a6a196]">Informe o CPF e o WhatsApp usados no cadastro. Você não precisa lembrar o protocolo.</p><label className="mt-6 block text-xs uppercase tracking-wider text-[#a6a196]">CPF<input required value={cpf} onChange={(e) => setCpf(maskCPF(e.target.value))} placeholder="000.000.000-00" inputMode="numeric" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-[#f3f1ea] outline-none focus:border-[#c6ff4d]" /></label><label className="mt-4 block text-xs uppercase tracking-wider text-[#a6a196]">WhatsApp<input required value={phone} onChange={(e) => setPhone(maskWhatsApp(e.target.value))} placeholder="(00) 00000-0000" inputMode="tel" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-[#f3f1ea] outline-none focus:border-[#c6ff4d]" /></label>{error && <p className="mt-4 rounded-xl border border-red-500/40 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<button disabled={busy} className="mt-6 flex w-full items-center justify-center gap-2 rounded-full bg-[#c6ff4d] px-4 py-3.5 text-sm font-bold uppercase text-[#171615] disabled:opacity-50">{busy && <Loader2 className="animate-spin" size={16} />}Acessar minha inscrição</button></form></main>;
}
