import { ArrowRight, CheckCircle2 } from "lucide-react";
import { CATEGORY_LABELS, RegistrationResult } from "../types/registration";

function SummaryItem({ label, value }: { label: string; value: string }) {
  return <div className="rounded-lg border border-white/10 bg-[#171615] px-3 py-2.5 text-left"><div className="font-mono text-[10px] uppercase tracking-widest text-[#6e6a60]">{label}</div><div className="mt-0.5 truncate text-sm text-[#f3f1ea]">{value}</div></div>;
}

export function RegistrationSuccess({ result, onContinue }: { result: RegistrationResult; onContinue: () => void }) {
  return <div className="rounded-xl border p-6 text-center sm:p-8" style={{ borderColor: "rgba(198,255,77,0.3)", background: "#201f1d" }}><div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full" style={{ background: "rgba(198,255,77,0.1)" }}><CheckCircle2 size={24} color="#C6FF4D" /></div><h2 className="text-xl font-bold uppercase text-[#f3f1ea]" style={{ fontFamily: "'Space Grotesk', sans-serif" }}>Cadastro recebido</h2><p className="mt-2 text-sm leading-relaxed text-[#a6a196]">Seus dados foram registrados. Agora faça o pagamento e envie o comprovante para concluir a inscrição.</p><div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-3"><SummaryItem label="Piloto" value={result.fullName} /><SummaryItem label="Veículo" value={result.vehicle} /><SummaryItem label="Categoria" value={CATEGORY_LABELS[result.category]} /></div><div className="mt-4 rounded-lg border border-dashed py-3 font-mono text-xs text-[#a6a196]" style={{ borderColor: "#3a3836" }}>Protocolo <span className="font-semibold text-[#f3f1ea]">{result.protocol}</span></div><button type="button" onClick={onContinue} className="mt-6 flex w-full items-center justify-center gap-2 rounded-full bg-[#c6ff4d] py-3.5 text-sm font-bold uppercase tracking-wide text-[#171615] transition-transform duration-150 hover:scale-[1.01] active:scale-[0.99]"><span>Ir para pagamento</span><ArrowRight size={16} /></button></div>;
}
